#!/usr/bin/env bash
# Refocus Shell - Main entry point
# Copyright (C) 2025 PeGa
# Website: https://www.pega.sh
# Email: dev@pega.sh
# Licensed under the GNU General Public License v3

# Main entry point for refocus shell
# Command dispatcher and argument parser

LIB_PATH="$(dirname "${BASH_SOURCE[0]}")/lib"
source "$LIB_PATH/error_handling.sh"

case "$1" in
    on)
        shift
        [ "$#" -ne 1 ] && _error_invalid_argument 1 $# "$*"
        exec "$LIB_PATH/on.sh" "$@"
        ;;
    off)
        [ "$#" -ne 0 ] && _error_invalid_argument 0 $# "$*"
        exec "$LIB_PATH/off.sh"
        ;;
    *)
        echo "Unknown command: $1"
        exit 1
        ;;
esac